services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/public:/var/www/public
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/ssl:/etc/ssl
    depends_on:
      - php
    environment:
      - TZ=Europe/Stockholm

  php:
    build: ./docker/php
    container_name: php
    volumes:
      - ./www:/var/www
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
    environment:
      - TZ=Europe/Stockholm

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    volumes:
      - ./db:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=db
      - MYSQL_USER=pma
      - MYSQL_PASSWORD=12345
      - TZ=Europe/Stockholm

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: always
    environment:
      - PMA_HOST=mariadb
      - TZ=Europe/Stockholm
    ports:
      - 8080:80
    depends_on:
      - mariadb

networks:
  docker-lemp-network: